// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaNotas.Infrastructure.Data;

#nullable disable

namespace SistemaNotas.Infrastructure.Migrations
{
    [DbContext(typeof(NotasDbContext))]
    [Migration("20260815055019_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaNotas.Domain.Entities.Ancla", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConceptoClave")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<bool>("RecordatorioVisual")
                        .HasColumnType("bit");

                    b.Property<Guid>("SeccionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("SeccionId");

                    b.ToTable("Anclas", (string)null);
                });

            modelBuilder.Entity("SistemaNotas.Domain.Entities.CategoriaAncla", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("CodigoColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("CategoriasAncla");
                });

            modelBuilder.Entity("SistemaNotas.Domain.Entities.Presentacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Audiencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("FechaExposicion")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("Presentaciones", (string)null);
                });

            modelBuilder.Entity("SistemaNotas.Domain.Entities.Retrospectiva", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MuletillasDetectadas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NivelNerviosismo")
                        .HasColumnType("int");

                    b.Property<Guid>("PresentacionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("QueSalioBien")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("PresentacionId")
                        .IsUnique();

                    b.ToTable("Retrospectivas", (string)null);
                });

            modelBuilder.Entity("SistemaNotas.Domain.Entities.Seccion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("MinutosEstimados")
                        .HasColumnType("int");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<Guid>("PresentacionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TituloSeccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("PresentacionId");

                    b.ToTable("Secciones", (string)null);
                });

            modelBuilder.Entity("SistemaNotas.Domain.Entities.Ancla", b =>
                {
                    b.HasOne("SistemaNotas.Domain.Entities.CategoriaAncla", "Categoria")
                        .WithMany("Anclas")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaNotas.Domain.Entities.Seccion", "Seccion")
                        .WithMany("Anclas")
                        .HasForeignKey("SeccionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Seccion");
                });

            modelBuilder.Entity("SistemaNotas.Domain.Entities.Retrospectiva", b =>
                {
                    b.HasOne("SistemaNotas.Domain.Entities.Presentacion", "Presentacion")
                        .WithOne("Retrospectiva")
                        .HasForeignKey("SistemaNotas.Domain.Entities.Retrospectiva", "PresentacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Presentacion");
                });

            modelBuilder.Entity("SistemaNotas.Domain.Entities.Seccion", b =>
                {
                    b.HasOne("SistemaNotas.Domain.Entities.Presentacion", "Presentacion")
                        .WithMany("Secciones")
                        .HasForeignKey("PresentacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Presentacion");
                });

            modelBuilder.Entity("SistemaNotas.Domain.Entities.CategoriaAncla", b =>
                {
                    b.Navigation("Anclas");
                });

            modelBuilder.Entity("SistemaNotas.Domain.Entities.Presentacion", b =>
                {
                    b.Navigation("Retrospectiva");

                    b.Navigation("Secciones");
                });

            modelBuilder.Entity("SistemaNotas.Domain.Entities.Seccion", b =>
                {
                    b.Navigation("Anclas");
                });
#pragma warning restore 612, 618
        }
    }
}
