// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaNotas.Infrastructure.Data;

#nullable disable

namespace SistemaNotas.Infrastructure.Migrations
{
    [DbContext(typeof(NotasDbContext))]
    [Migration("20260816180650_AgregarSeedData")]
    partial class AgregarSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaNotas.Domain.Entities.Ancla", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConceptoClave")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<bool>("RecordatorioVisual")
                        .HasColumnType("bit");

                    b.Property<Guid>("SeccionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("SeccionId");

                    b.ToTable("Anclas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("ff100001-1111-1111-1111-111111111111"),
                            CategoriaId = new Guid("cc111111-1111-1111-1111-111111111111"),
                            ConceptoClave = "Diferencias en memoria: Stack vs Heap",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 16, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Orden = 1,
                            RecordatorioVisual = false,
                            SeccionId = new Guid("bb100001-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("ff300001-3333-3333-3333-333333333333"),
                            CategoriaId = new Guid("cc111111-1111-1111-1111-111111111111"),
                            ConceptoClave = "Enfatizar interoperabilidad entre dependencias",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 16, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Orden = 1,
                            RecordatorioVisual = false,
                            SeccionId = new Guid("bb300001-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("ff300002-3333-3333-3333-333333333333"),
                            CategoriaId = new Guid("cc222222-2222-2222-2222-222222222222"),
                            ConceptoClave = "Abrir Postman para mostrar el intercambio del JWT",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 16, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Orden = 1,
                            RecordatorioVisual = true,
                            SeccionId = new Guid("bb300002-3333-3333-3333-333333333333")
                        });
                });

            modelBuilder.Entity("SistemaNotas.Domain.Entities.CategoriaAncla", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("CodigoColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("CategoriasAncla");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cc111111-1111-1111-1111-111111111111"),
                            Activo = true,
                            CodigoColor = "#3498db",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 16, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Nombre = "Concepto Clave"
                        },
                        new
                        {
                            Id = new Guid("cc222222-2222-2222-2222-222222222222"),
                            Activo = true,
                            CodigoColor = "#e74c3c",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 16, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Nombre = "Demo / Código en Vivo"
                        },
                        new
                        {
                            Id = new Guid("cc333333-3333-3333-3333-333333333333"),
                            Activo = true,
                            CodigoColor = "#f1c40f",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 16, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Nombre = "Pregunta a Audiencia"
                        },
                        new
                        {
                            Id = new Guid("cc444444-4444-4444-4444-444444444444"),
                            Activo = true,
                            CodigoColor = "#2ecc71",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 16, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Nombre = "Alerta de Tiempo"
                        });
                });

            modelBuilder.Entity("SistemaNotas.Domain.Entities.Presentacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Audiencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("FechaExposicion")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Presentaciones", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aa111111-1111-1111-1111-111111111111"),
                            Audiencia = "Trainees",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 16, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FechaExposicion = new DateTimeOffset(new DateTime(2026, 8, 26, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Titulo = "Aprender C# desde cero: Fundamentos",
                            UsuarioId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("aa222222-2222-2222-2222-222222222222"),
                            Audiencia = "Frontend Devs",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 16, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FechaExposicion = new DateTimeOffset(new DateTime(2026, 9, 5, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Titulo = "Angular con Signals y Standalone",
                            UsuarioId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("aa333333-3333-3333-3333-333333333333"),
                            Audiencia = "Arquitectos",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 16, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FechaExposicion = new DateTimeOffset(new DateTime(2026, 9, 15, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Titulo = "Implementación de LlaveMX en Gobierno",
                            UsuarioId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("SistemaNotas.Domain.Entities.Retrospectiva", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MuletillasDetectadas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NivelNerviosismo")
                        .HasColumnType("int");

                    b.Property<Guid>("PresentacionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("QueSalioBien")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("PresentacionId")
                        .IsUnique();

                    b.ToTable("Retrospectivas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("ee100001-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 16, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            MuletillasDetectadas = "[\"este\",\"entonces\"]",
                            NivelNerviosismo = 3,
                            PresentacionId = new Guid("aa111111-1111-1111-1111-111111111111"),
                            QueSalioBien = "La interacción con los juniors al explicar Clean Architecture fue muy fluida."
                        });
                });

            modelBuilder.Entity("SistemaNotas.Domain.Entities.Seccion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("MinutosEstimados")
                        .HasColumnType("int");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<Guid>("PresentacionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TituloSeccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("PresentacionId");

                    b.ToTable("Secciones", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("bb100001-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 16, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            MinutosEstimados = 15,
                            Orden = 1,
                            PresentacionId = new Guid("aa111111-1111-1111-1111-111111111111"),
                            TituloSeccion = "Introducción al CLR"
                        },
                        new
                        {
                            Id = new Guid("bb300001-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 16, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            MinutosEstimados = 15,
                            Orden = 1,
                            PresentacionId = new Guid("aa333333-3333-3333-3333-333333333333"),
                            TituloSeccion = "Marco Normativo OIDC"
                        },
                        new
                        {
                            Id = new Guid("bb300002-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 16, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            MinutosEstimados = 30,
                            Orden = 2,
                            PresentacionId = new Guid("aa333333-3333-3333-3333-333333333333"),
                            TituloSeccion = "Login y Tokens en .NET Core"
                        });
                });

            modelBuilder.Entity("SistemaNotas.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 16, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "ed@mymail.com",
                            IsDeleted = false,
                            Nombre = "Eduardo Campos",
                            PasswordHash = "$2a$11$H5...hash_simulado_seguro..."
                        });
                });

            modelBuilder.Entity("SistemaNotas.Domain.Entities.Ancla", b =>
                {
                    b.HasOne("SistemaNotas.Domain.Entities.CategoriaAncla", "Categoria")
                        .WithMany("Anclas")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaNotas.Domain.Entities.Seccion", "Seccion")
                        .WithMany("Anclas")
                        .HasForeignKey("SeccionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Seccion");
                });

            modelBuilder.Entity("SistemaNotas.Domain.Entities.Presentacion", b =>
                {
                    b.HasOne("SistemaNotas.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Presentaciones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaNotas.Domain.Entities.Retrospectiva", b =>
                {
                    b.HasOne("SistemaNotas.Domain.Entities.Presentacion", "Presentacion")
                        .WithOne("Retrospectiva")
                        .HasForeignKey("SistemaNotas.Domain.Entities.Retrospectiva", "PresentacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Presentacion");
                });

            modelBuilder.Entity("SistemaNotas.Domain.Entities.Seccion", b =>
                {
                    b.HasOne("SistemaNotas.Domain.Entities.Presentacion", "Presentacion")
                        .WithMany("Secciones")
                        .HasForeignKey("PresentacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Presentacion");
                });

            modelBuilder.Entity("SistemaNotas.Domain.Entities.CategoriaAncla", b =>
                {
                    b.Navigation("Anclas");
                });

            modelBuilder.Entity("SistemaNotas.Domain.Entities.Presentacion", b =>
                {
                    b.Navigation("Retrospectiva");

                    b.Navigation("Secciones");
                });

            modelBuilder.Entity("SistemaNotas.Domain.Entities.Seccion", b =>
                {
                    b.Navigation("Anclas");
                });

            modelBuilder.Entity("SistemaNotas.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Presentaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
